from typing import Any

def manager_repr(value: Any) -> Any: ...
def smart_repr(value: Any) -> Any: ...
def field_repr(field: Any, force_many: bool = ...) -> Any: ...
def serializer_repr(serializer: Any, indent: Any, force_many: Any | None = ...) -> Any: ...
def list_repr(serializer: Any, indent: Any) -> Any: ...
