from re import Pattern
from typing import Any, NamedTuple

from coreschema.compat import numeric_types as numeric_types
from coreschema.compat import text_types as text_types
from coreschema.formats import validate_format as validate_format
from coreschema.utils import uniq as uniq

class Error(NamedTuple):
    text: str
    index: list[str]  # type: ignore [assignment]

def push_index(errors: list[Error], key: Any) -> list[str]: ...

class Schema:
    errors: list[Error] = ...
    title: Any = ...
    description: Any = ...
    default: Any = ...
    def __init__(self, title: str = ..., description: str = ..., default: Any | None = ...) -> None: ...
    def make_error(self, code: str) -> Error: ...
    def __or__(self, other: Schema) -> Union: ...
    def __and__(self, other: Schema) -> Intersection: ...
    def __xor__(self, other: Schema) -> ExclusiveUnion: ...
    def __invert__(self) -> Not: ...
    def __eq__(self, other: Schema) -> bool: ...  # type: ignore [override]

class Object(Schema):
    errors: list[Error] = ...
    additional_properties_schema: Any = ...
    properties: Any = ...
    required: bool | None = ...
    max_properties: int = ...
    min_properties: int = ...
    pattern_properties: Any = ...
    additional_properties: Any = ...
    pattern_properties_regex: Any = ...
    def __init__(
        self,
        properties: Any | None = ...,
        required: bool | None = ...,
        max_properties: Any | None = ...,
        min_properties: Any | None = ...,
        pattern_properties: Any | None = ...,
        additional_properties: bool = ...,
        **kwargs: Any
    ) -> None: ...
    def validate(self, value: Any, context: Any | None = ...) -> list[Error]: ...

class Array(Schema):
    errors: list[Error] = ...
    items: Schema = ...
    max_items: int = ...
    min_items: int = ...
    unique_items: int = ...
    additional_items: int = ...
    def __init__(
        self,
        items: Any | None = ...,
        max_items: Any | None = ...,
        min_items: Any | None = ...,
        unique_items: bool = ...,
        additional_items: bool = ...,
        **kwargs: Any
    ) -> None: ...
    def validate(self, value: Any, context: Any | None = ...) -> list[Error]: ...

class Number(Schema):
    integer_only: bool = ...
    errors: list[Error] = ...
    minimum: int = ...
    maximum: int = ...
    exclusive_minimum: int = ...
    exclusive_maximum: int = ...
    multiple_of: int | None = ...
    def __init__(
        self,
        minimum: int | None = ...,
        maximum: int | None = ...,
        exclusive_minimum: bool = ...,
        exclusive_maximum: bool = ...,
        multiple_of: int | None = ...,
        **kwargs: Any
    ) -> None: ...
    def validate(self, value: Any, context: Any | None = ...) -> list[Error]: ...

class Integer(Number):
    errors: list[Error] = ...
    integer_only: bool = ...

class String(Schema):
    errors: list[Error] = ...
    max_length: Any = ...
    min_length: Any = ...
    pattern: str = ...
    format: str = ...
    pattern_regex: Pattern[str] = ...
    def __init__(
        self,
        max_length: int | None = ...,
        min_length: int | None = ...,
        pattern: str | None = ...,
        format: Any | None = ...,
        **kwargs: Any
    ) -> None: ...
    def validate(self, value: Any, context: Any | None = ...) -> list[Error]: ...

class Boolean(Schema):
    errors: list[Error] = ...
    def validate(self, value: Any, context: Any | None = ...) -> list[Error]: ...

class Null(Schema):
    errors: list[Error] = ...
    def validate(self, value: Any, context: Any | None = ...) -> list[Error]: ...

class Enum(Schema):
    errors: list[Error] = ...
    enum: Any = ...
    exact: Any = ...
    def __init__(self, enum: Any, **kwargs: Any) -> None: ...
    def validate(self, value: Any, context: Any | None = ...) -> list[Error]: ...

class Anything(Schema):
    errors: list[Error] = ...
    types: Any = ...
    def validate(self, value: Any, context: Any | None = ...) -> list[Error]: ...

class Union(Schema):
    errors: list[Error] = ...
    children: list[Schema] = ...
    def __init__(self, children: list[Schema], **kwargs: Any) -> None: ...
    def validate(self, value: Any, context: Any | None = ...) -> list[Error]: ...

class Intersection(Schema):
    children: list[Schema] = ...
    def __init__(self, children: list[Schema], **kwargs: Any) -> None: ...
    def validate(self, value: Any, context: Any | None = ...) -> list[Error]: ...

class ExclusiveUnion(Schema):
    errors: list[Error] = ...
    children: list[Schema] = ...
    def __init__(self, children: list[Schema], **kwargs: Any) -> None: ...
    def validate(self, value: Any, context: Any | None = ...) -> list[Error]: ...

class Not(Schema):
    errors: list[Error] = ...
    child: Any = ...
    def __init__(self, child: Any, **kwargs: Any) -> None: ...
    def validate(self, value: Any, context: Any | None = ...) -> list[Error]: ...

class Ref(Schema):
    ref_name: Any = ...
    def __init__(self, ref_name: Any) -> None: ...
    def dereference(self, context: Any) -> Any: ...
    def validate(self, value: Any, context: Any | None = ...) -> list[Error]: ...

class RefSpace(Schema):
    refs: Any = ...
    root: Any = ...
    root_validator: Any = ...
    def __init__(self, refs: Any, root: Any) -> None: ...
    def validate(self, value: Any) -> list[Error]: ...
